### ISSUE TITLE
Phonegap build error

### ISSUE THREAD

**Issue by canado** [andrehtissot/cordova-plugin-firebase-extended-notification#19]
I wanted to know if anyone managed to make this plugin work with 
Phonegap build

I have this error

:processReleaseGoogleServices
Found com.google.firebase:firebase-crash:+, but version 10.+ is needed for the google-services plugin.
Found com.google.android.gms:play-services-ads:+, but version 10.+ is needed for the google-services plugin.
Found com.google.android.gms:play-services-location:11.+, but version 10.+ is needed for the google-services plugin.
Found com.google.firebase:firebase-core:+, but version 10.+ is needed for the google-services plugin.
Found com.google.firebase:firebase-messaging:+, but version 10.+ is needed for the google-services plugin.
Found com.google.firebase:firebase-config:+, but version 10.+ is needed for the google-services plugin.
:processReleaseGoogleServices FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 10.+.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.247 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 10.+.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by andrehtissot** [comment]
Hi @canado, I build manually with cordova on terminal. But the solution may work with Phonegap build as well.

This dependency system is frustratingly dump sometimes.
Look in this line:
`Found com.google.android.gms:play-services-location:11.+, but version 10.+ is needed for the google-services plugin.`

If one plugin require 10 or newer and the other require 11 or newer, why not just use the newer available? No... for some reason those dependencies conflict. But without dependencies defined, the library is not included in the build, ... so they cannot be avoided.

Sadly, leaving `:+` (without any number) doesn't work, usually, for firebase, defaulting to version 9. Which does not work properly in some cases.


To help you work-around this, can you list here your plugins (something like `cordova plugin list`)?

Because even if I change the dependency for the last version, being 10+, 11+ or higher, there are other dependencies in your case like `Found com.google.firebase:firebase-crash:+` which would conflict with a defined "last" version.

**Comment by andrehtissot** [comment]
Closed due to lack of user's answer.
