### ISSUE TITLE
don't show notifications

### ISSUE THREAD

**Issue by iamcodered** [andrehtissot/cordova-plugin-firebase-extended-notification#27]
Is it possible not to show the received notification depending on the variables? I write the interface where the user chooses to show him notifications or not. or better to do on the server side?

**Comment by andrehtissot** [comment]
When the application is on the background or foreground, yes.
You can send the notification without the `notificationOptions` and from the app `FirebaseExtendedNotification.showNotification({}, {})` as documented.

The issue comes when you want to control this when the app is closed. As in that case, the cordova part is not callable, requiring changes on the `onMessageReceived` of `src/android/MessagingService.java`.

**Comment by andrehtissot** [comment]
If you send in the "right way" from the server side, you'll not face this kind of issue.
