### ISSUE TITLE
cannot play sound in the res folder

### ISSUE THREAD

**Issue by januarsy** [andrehtissot/cordova-plugin-firebase-extended-notification#29]
why can't play sound on cordova-android 7.1.1?

on Cordova-Android 6.2.3 it works well, but after upgrade Cordova-Android 7.1.1 it doesn't work.

I see something different in the folder location

@ 6.2.3 => res \ raw
@ 7.1.1 => app \ src \ main \ res \ raw

how can this return to work on cordova-android 7.1.1?

**Comment by andrehtissot** [comment]
Thank you for letting me know. I'll investigate.

**Comment by andrehtissot** [comment]
Yes @januarsy, it should work after moving the sound files from the old dir to the app's `platforms/android/app/src/main/res/raw`.

The was a bug found for sound options on Android 8+, due to sound been set on Notification Channel. This bug was fixed in the version 1.10.1.

Remember to, when experimenting, use different channel ids, so new configurations can be applied in Android 8+.

If issues continue, please don't hesitate to create another issue ticket.
