### ISSUE TITLE
"openApp": true option not working on Android 10

### ISSUE THREAD

**Issue by efizzy** [andrehtissot/cordova-plugin-firebase-extended-notification#34]
Hello @andrehtissot 

Currently using this plugin on Android 10 and the "openApp": true option not working. Any ideal why this is so?

**Comment by andrehtissot** [comment]
I'll check

**Comment by andrehtissot** [comment]
The openApp feature deprecated due to Android 10 new restrictions: https://developer.android.com/guide/components/activities/background-starts

Not being part of the system, the only way to open the app from the background only allows the presentation of an overlay (https://developer.android.com/reference/android/Manifest.permission#SYSTEM_ALERT_WINDOW), not the app itself.

**Comment by andrehtissot** [comment]
Thank you for letting me know.
